server:
  port: 8080
  servlet:
    context-path: /WDA
    jsp:
      init-parameters:
        development: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://121.199.0.105:3306/db_dongbang?serverTimezone=UTC
    url: jdbc:mysql://121.199.0.105:3306/wens_sub_health?serverTimezone=UTC
    username: root
    password: njau#B307
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-request-size: 10000MB
      max-file-size: 10000MB
